### ISSUE TITLE
https://www.npmjs.com/package/highcharts-more is broken

### ISSUE THREAD

**Issue by justin808** [kirjs/publish-highcharts-modules#1]
If you look in package.json, it's specifying the wrong main file.

The filename is "more.js" and not "highcharts-more.js".

![2015-12-05_00-09-08](https://cloud.githubusercontent.com/assets/1118459/11607278/725ccd7a-9ae4-11e5-93c7-3cc6a44d63e7.png)

**Comment by kirjs** [comment]
Thanks a lot, should be fixed now.
