### ISSUE TITLE
Update to the latest version

### ISSUE THREAD

**Issue by kirjs** [kirjs/publish-highcharts-modules#3]
Should fix this:
https://github.com/kirjs/react-highcharts/issues/72#issuecomment-169091416

**Comment by kirjs** [comment]
@martin-svk  Try using `highcharts-more@0.0.8` and `highcharts-exporting@0.0.8`, let me know if thatimproves the situation.

**Comment by martin-svk** [comment]
Hi, I just updated the libs and tried this:

``` javascript
import ReactHighcharts from 'react-highcharts/bundle/highcharts';
import 'highcharts-exporting';
import 'highcharts-more';
```

And it no longer fails with `HighchartsAdapter is not defined` but I am still getting the series type does not exist error: `http://www.highcharts.com/errors/17`. When trying to use `solidgauge`.

**Comment by kirjs** [comment]
See this line https://github.com/kirjs/react-highcharts/blob/master/demo/src/more.jsx#L4
Let me know if this works

**Comment by martin-svk** [comment]
So I did:

``` javascript
global.Highcharts = require('highcharts');
const HighchartsMore = require('highcharts-more');
HighchartsMore(global.Highcharts );
const ReactHighcharts = require('react-highcharts');
```

And I was able to display for example a `polar` graph. But not `solidgauge`. It seems to need to load additional `highcharts-solidgauge` module.

I am guessing based on their official `solidgauge` jsfiddle demo:

``` html
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/solid-gauge.js"></script>
```

But that is probably no longer in the scope of this issue. But I still dont like the need
to use the old `require` statements intead of `import`. 

Anyway, following Your demo, It looks like `highcharts-more` is successfully imported. Thanks for Your time.

**Comment by kirjs** [comment]
I don't think you have to use require, don't see why import would not work here
