### ISSUE TITLE
how to use "highcharts-boost"?

### ISSUE THREAD

**Issue by hank7444** [kirjs/publish-highcharts-modules#4]
That is my code, but it doesn't make any impovement

PS: I use highstock and use websocket get point every 500ms

![image](https://cloud.githubusercontent.com/assets/4727090/12471656/a852e3da-c03a-11e5-9bc0-2a3ee2311356.png)

**Comment by kirjs** [comment]
My guess is that you have to do something like `HighchartsBoost(Highcharts);`

**Comment by hank7444** [comment]
@kirjs I'll try it, thx!

**Comment by hank7444** [comment]
@kirjs it's not work because  react-highcharts is react component which warpped the real highchart object :(

**Comment by kirjs** [comment]
Rename  `Highcharts` to  `ReactHighcharts`, you should have a global `Highcharts` var which has been shadowed.

**Comment by hank7444** [comment]
I followed the example, it works now, thx! 
![image](https://cloud.githubusercontent.com/assets/4727090/12515159/f030bb14-c161-11e5-9ed2-c922e3aa0bf5.png)
