### ISSUE TITLE
highcharts-more pointing to old version.

### ISSUE THREAD

**Issue by bofa** [kirjs/publish-highcharts-modules#5]
Latest version of highcharts more is v4.2.3

The npm module as of now is delivering v4.2.1

There is a bug in v4.2.1 that i like to get rid of when using npm. =)

**Comment by kirjs** [comment]
Thanks, I'll update it over the weekend

**Comment by bofa** [comment]
Thank you very much!

**Comment by kirjs** [comment]
The latest version should have the latest version :)
