### ISSUE TITLE
Chart using highcharts-solid-gauge doesn't animate on render

### ISSUE THREAD

**Issue by raluca-stan** [kirjs/publish-highcharts-modules#7]
I render a chart with the config from [here](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/gauge-activity/) in my React component, using react-highcharts, but the chart doesn't animate.

**Comment by raluca-stan** [comment]
Rendered this without react-highcharts and all is good. Closing issue.

**Comment by alijalbani** [comment]
Hi raluca.. What do you mean rendered it without highcharts? I have the same issue... it doesnt animate

**Comment by marc-morris** [comment]
I also can't get a solid gauge chart to animate. My team got around it with a bit of a hack, but the animation isn't as good as the build in animation.

` componentDidMount() {
        const chart = this.refs.chart.getChart();
        const y = this.props.data;
        const updateChartInterval = setInterval(() => {
            updateChart(chart, y, updateChartInterval);
        }, 100);
    }`
